# Generated by Django 4.1.1 on 2022-10-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('order_number', models.IntegerField()),
                ('delivery_time', models.DateField()),
                ('price_usd', models.FloatField()),
                ('price_rub', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
