# Generated by Django 4.1.1 on 2022-10-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('chat_id', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
